baseURL = "https://martinry.netlify.app/"
languageCode = "en-us"
title = "~/"
theme = "ezhil"

copyright = "© Copyright notice"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    description = "Just tryin' to make a change :/"
    github  = "https://github.com/martinry"
    linkedin = "https://www.linkedin.com/in/martin-ryd%C3%A9n-64039146/"
    twitter = "https://twitter.com/martinryden89"
    instagram = "https://www.instagram.com/maartinry/"
    background_color_class = "bg-near-black"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/vividvilla/ezhil"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"