baseURL = "https://boring-knuth-25c4c8.netlify.app/"
languageCode = "en-us"
title = "Martin Rydén's PhD Portfolio"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    description = "Just tryin' to make a change :/"
    github  = "https://github.com/martinry"
    linkedin = "https://www.linkedin.com/in/martin-ryd%C3%A9n-64039146/"
    twitter = "https://twitter.com/martinryden89"
    instagram = "https://www.instagram.com/maartinry/"
    background_color_class = "bg-near-black"
    featured_image = "/images/brown-carriage-wheel-672630.jpg"
    recent_posts_number = 5
    custom_css = ["css/custom.css"]

[[params.footer.quicklinks]]
    text = "Code of Conduct"
    link = "posts/code-of-conduct"
