baseURL = "https://martinry.netlify.app/"
languageCode = "en-us"
title = "~/"
theme = "hugo-notepadium"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
description = "Just tryin' to make a change :/"
github  = "https://github.com/martinry"
linkedin = "https://www.linkedin.com/in/martin-ryd%C3%A9n-64039146/"
twitter = "https://twitter.com/martinryden89"
instagram = "https://www.instagram.com/maartinry/"
background_color_class = "bg-near-black"
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Jan 02, 2006"  # if unset, default is "2006-01-02"
readingTime = false  # show reading time after article date
logo = ""
slogan = "100% JavaScript-free"
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

[params.assets]
css = ["css/fonts.css"]
